### PR TITLE
CEREBRAL-1370 Release flora-sql-parser v1.2.0

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [CEREBRAL-2093 Handle adding an optional system for the ast parser](https://github.com/Workiva/flora-sql-parser/pull/42)

Requested by: @patrickofriel-wk

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/flora-sql-parser/compare/v1.1.2...Workiva:release_flora-sql-parser_v1.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/flora-sql-parser/compare/v1.1.2...v1.2.0

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5408643242000384/logs/)

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by patrickofriel-wk** [comment]
+10

**Comment by matthewhatch-wk** [comment]
+1

**Review by jasonclouse-wk — APPROVED** [review]
+1

**Comment by patrickofriel-wk** [comment]
@Workiva/release-management-p

**Pull request merged**
