### PR TITLE
CEREBRAL-2180 Parameters can start with number

### PR DESCRIPTION
**Pull request by jessicashelton-wk**
###### Overview:
Parameters that start with a number were not being parsed correctly.

###### How To Test:
Ensure unit tests run

###### Reviewers:
@Workiva/scout-team

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by dougthomas-wk** [comment]
+1

**Comment by chrisphillips-wk** [comment]
+1

**Comment by jessicashelton-wk** [comment]
QA +1

**Comment by jessicashelton-wk** [comment]
@Workiva/release-management-p

**Pull request merged**
