### PR TITLE
CEREBRAL-2093 Handle adding an optional system for the ast parser

### PR DESCRIPTION
**Pull request by patrickofriel-wk**
###### Overview:
Add an optional 'system' property for tables

###### How To Test:
Unit tests pass.

###### Reviewers:
@patrickofriel-wk
@dustinhiatt-wf
@chrisphillips-wk 
@davidgiametta-wk

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by jessicashelton-wk** [comment]
+1

**Comment by patrickofriel-wk** [comment]
QA +1

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by patrickofriel-wk** [comment]
@Workiva/release-management-p

**Comment by patrickofriel-wk** [comment]
@Workiva/release-management-p

**Pull request merged**
